version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: verb_verse
    ports:
      - "8001:5432"

  keycloak:
    image: bitnami/keycloak:24
    ports:
      - "8180:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: verb_verse
      DB_SCHEMA: public
      DB_USER: postgres
      DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
    depends_on:
      - postgres

volumes:
  pg_data:
    name: pg_data
