version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: verb_verse
      ports:
        '5432:5432'

volumes:
  pg_data:
    name: pg_data
