server:
  port: 8765
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: education_route
          uri: lb://EDUCATION-SERVICE
          predicates:
            - Path=/education/**
          filters:
            - StripPrefix=1
        - id: user_route
          uri: lb://USER-SERVICE
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  pattern:
    console: "%cyan(%d{YY-MM-dd HH:mm:ss.SSS}) %clr(%-5level) %file line:%line [%magenta(%logger{36})] : %msg%n"
